import 'package:flutter/material.dart';
import 'home_screen.dart';
import 'map_screen.dart';
import 'calculator_screen.dart';
import 'compare_screen.dart';

class AboutScreen extends StatelessWidget {
  const AboutScreen({super.key});

  void _onNavTap(BuildContext context, int index) {
    switch (index) {
      case 0:
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (_) => const HomeScreen(),
          ),
        );
        break;

      case 1:
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (_) => const MapScreen(),
          ),
        );
        break;

      case 2:
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (_) => const CalculatorScreen(),
          ),
        );
        break;

      case 3:
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (_) => const CompareScreen(),
          ),
        );
        break;

      case 4:
        break;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xff040607),

      bottomNavigationBar: BottomNavigationBar(
        currentIndex: 4,
        backgroundColor: const Color(0xff040607),
        selectedItemColor: const Color(0xffBF40FA),
        unselectedItemColor: const Color(0xffE3D9FC),
        type: BottomNavigationBarType.fixed,
        onTap: (index) => _onNavTap(context, index),
        items: const [
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: "Home",
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.map),
            label: "Map",
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.calculate),
            label: "Calc",
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.bar_chart),
            label: "Compare",
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.info),
            label: "About",
          ),
        ],
      ),

      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(24),

          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Center(
                child: Icon(
                  Icons.auto_awesome,
                  color: Color(0xffBF40FA),
                  size: 70,
                ),
              ),

              const SizedBox(height: 15),

              const Center(
                child: Text(
                  "Aionia",
                  style: TextStyle(
                    fontSize: 36,
                    fontWeight: FontWeight.bold,
                    color: Color(0xffE3D9FC),
                    letterSpacing: 2,
                  ),
                ),
              ),

              const SizedBox(height: 8),

              const Center(
                child: Text(
                  "AI Sustainability Platform",
                  style: TextStyle(
                    color: Color(0xffBF40FA),
                    fontSize: 14,
                    letterSpacing: 1.5,
                  ),
                ),
              ),

              const SizedBox(height: 30),

              Container(
                padding: const EdgeInsets.all(20),
                decoration: BoxDecoration(
                  color: const Color(0xff5B2A62),
                  borderRadius: BorderRadius.circular(22),
                  boxShadow: const [
                    BoxShadow(
                      color: Colors.black38,
                      blurRadius: 15,
                      offset: Offset(0, 8),
                    ),
                  ],
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: const [
                    Text(
                      "Aionia (Αἰωνία) means 'Eternal Life' in Greek.",
                      style: TextStyle(
                        fontSize: 16,
                        color: Color(0xffE3D9FC),
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                    SizedBox(height: 15),
                    Text(
                      "This application estimates the environmental impact of AI usage including electricity consumption, water usage and carbon emissions generated by modern AI models.",
                      style: TextStyle(
                        fontSize: 15,
                        color: Colors.white70,
                        height: 1.6,
                      ),
                    ),
                  ],
                ),
              ),

              const SizedBox(height: 25),

              _sectionCard(
                title: "🌍 MAP SYSTEM",
                content:
                "The map visualizes global AI infrastructure and estimated server regions used by GPT, Claude and Gemini models.",
              ),

              const SizedBox(height: 18),

              _sectionCard(
                title: "🤖 SUPPORTED MODELS",
                content:
                "GPT-5.2, GPT-5.3, GPT-5.4, Haiku 4.6, Sonnet 4.6, Opus 4.6, Gemini 2.5 Flash, Gemini 2.5 Pro and Gemini 3.1 Pro.",
              ),

              const SizedBox(height: 18),

              _sectionCard(
                title: "🎨 DESIGN LANGUAGE",
                content:
                "The interface uses cyber-inspired purple and blue tones to represent advanced AI systems while maintaining readability and modern aesthetics.",
              ),

              const SizedBox(height: 18),

              _sectionCard(
                title: "⚠ DISCLAIMER",
                content:
                "All environmental calculations are approximate estimates intended for educational and research purposes.",
              ),

              const SizedBox(height: 30),

              SizedBox(
                width: double.infinity,
                height: 58,
                child: ElevatedButton(
                  onPressed: () {
                    Navigator.pop(context);
                  },
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xffE3D9FC),
                    foregroundColor: Colors.black,
                    elevation: 10,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(18),
                    ),
                  ),
                  child: const Text(
                    "⬅ Back",
                    style: TextStyle(
                      fontWeight: FontWeight.bold,
                      fontSize: 16,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  static Widget _sectionCard({
    required String title,
    required String content,
  }) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(18),
      decoration: BoxDecoration(
        color: const Color(0xff0F1117),
        borderRadius: BorderRadius.circular(20),
        border: Border.all(
          color: const Color(0xffBF40FA),
          width: 1,
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: const TextStyle(
              color: Color(0xffE3D9FC),
              fontSize: 18,
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 10),
          Text(
            content,
            style: const TextStyle(
              color: Colors.white70,
              fontSize: 14,
              height: 1.6,
            ),
          ),
        ],
      ),
    );
  }
}